//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Command
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Command()
        {
            this.ResultCompetition = new HashSet<ResultCompetition>();
            this.SponsorCommand = new HashSet<SponsorCommand>();
            this.Sportsman = new HashSet<Sportsman>();
        }
    
        public int idCommand { get; set; }

        [Required(ErrorMessage = "Name command is required")]
        public string Name { get; set; }

        [Range(6, 12)]
        public Nullable<int> Count { get; set; }

        [Required(ErrorMessage = "Name city is required")]
        public Nullable<int> ID_city { get; set; }

        public byte[] Image { get; set; }

        public bool IsDeleted { get; set; }
    
        public virtual City City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResultCompetition> ResultCompetition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SponsorCommand> SponsorCommand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sportsman> Sportsman { get; set; }

        public override string ToString()
        {
            return $"{idCommand},{Name} {Count}";
        }
    }
}
