//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CompetitionExamEntities : DbContext
    {
        public CompetitionExamEntities()
            : base("name=CompetitionExamEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Competition> Competition { get; set; }
        public virtual DbSet<ResultCompetition> ResultCompetition { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Title> Title { get; set; }
        public virtual DbSet<TypeUser> TypeUser { get; set; }
        public virtual DbSet<Images> Images { get; set; }
        public virtual DbSet<Command> Command { get; set; }
        public virtual DbSet<Sportsman> Sportsman { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Sponsor> Sponsor { get; set; }
        public virtual DbSet<SponsorCommand> SponsorCommand { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
