//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultCompetitionSprint
    {
        public int idSportsman { get; set; }
        public int idCompetition { get; set; }
        public Nullable<int> Rank { get; set; }
    
        public virtual Competition Competition { get; set; }
        public virtual Sportsman Sportsman { get; set; }
    }
}
