//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.SponsorCommand = new HashSet<SponsorCommand>();
        }
    
        public int idUser { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<int> Year { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public Nullable<int> idType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SponsorCommand> SponsorCommand { get; set; }
        public virtual TypeUser TypeUser { get; set; }
    }
}
